'use client';
import { useState,useTransition } from 'react';
import { ShieldAlert } from 'lucide-react';
import { displayMoney } from '@/lib/display-format';
import { decideTitanRecommendationAction,updateAutonomyPolicyAction } from '@/app/(dashboard)/admin/titan/governance/actions';
type Row=Record<string,any>;const modes=['observe','recommend','prepare','approval_required','autopilot'];
export function TitanGovernanceClient({initialPolicies,outcomes}:{initialPolicies:Row[];outcomes:Row[]}){
 const [policies,setPolicies]=useState(initialPolicies);const [pending,start]=useTransition();const [msg,setMsg]=useState('');
 const accepted=outcomes.filter(x=>x.owner_decision==='accepted');const evaluated=outcomes.filter(x=>x.evaluated_at);const accuracy=evaluated.length?Math.round(evaluated.reduce((s,x)=>s+Number(x.accuracy??0),0)/evaluated.length*100):null;
 const update=(i:number,key:string,value:any)=>setPolicies(p=>p.map((x,n)=>n===i?{...x,[key]:value}:x));
 return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Accepted',accepted.length],['Ignored',outcomes.filter(x=>x.owner_decision==='ignored').length],['Revenue',displayMoney(outcomes.reduce((s,x)=>s+Number(x.revenue_cents??0),0))],['Margin',displayMoney(outcomes.reduce((s,x)=>s+Number(x.margin_cents??0),0))],['Prediction accuracy',accuracy==null?'No evaluated outcomes':`${accuracy}%`]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-border bg-card p-4"><p className="text-[10px] font-black uppercase text-muted-foreground">{l}</p><p className="mt-2 text-xl font-black">{v}</p></div>)}</section>
 <section className="rounded-3xl border border-gold/25 bg-card p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-black">Operating policies</h2><p className="text-xs text-muted-foreground">Autopilot remains bounded by consent, capacity, quiet hours, spend, discounts, audience, and approval thresholds.</p></div><button onClick={()=>setPolicies(p=>p.map(x=>({...x,emergency_stopped:true,mode:'observe'})))} className="inline-flex h-fit items-center gap-2 rounded-xl border border-rose-500/40 px-3 py-2 text-xs font-black uppercase text-rose-400"><ShieldAlert className="h-4 w-4"/>Emergency stop all</button></div>
 <div className="mt-5 overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-xs"><thead><tr className="text-[9px] uppercase text-muted-foreground">{['Workflow','Mode','Spend limit','Discount %','Audience','Approval $','Emergency',''].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{policies.map((p,i)=><tr key={p.workflow} className="border-t border-border"><td className="p-2 font-black">{String(p.workflow).replaceAll('_',' ')}</td><td className="p-2"><select value={p.mode} onChange={e=>update(i,'mode',e.target.value)} className="rounded-lg border border-border bg-input p-2">{modes.map(m=><option key={m} value={m}>{m.replaceAll('_',' ')}</option>)}</select></td><td className="p-2"><input type="number" value={p.spending_limit_cents/100} onChange={e=>update(i,'spending_limit_cents',Number(e.target.value)*100)} className="w-24 rounded-lg border border-border bg-input p-2"/></td><td className="p-2"><input type="number" value={p.discount_limit_bps/100} onChange={e=>update(i,'discount_limit_bps',Number(e.target.value)*100)} className="w-20 rounded-lg border border-border bg-input p-2"/></td><td className="p-2"><input type="number" value={p.audience_limit} onChange={e=>update(i,'audience_limit',Number(e.target.value))} className="w-20 rounded-lg border border-border bg-input p-2"/></td><td className="p-2"><input type="number" value={p.approval_threshold_cents/100} onChange={e=>update(i,'approval_threshold_cents',Number(e.target.value)*100)} className="w-24 rounded-lg border border-border bg-input p-2"/></td><td className="p-2"><input type="checkbox" checked={p.emergency_stopped} onChange={e=>update(i,'emergency_stopped',e.target.checked)}/></td><td className="p-2"><button disabled={pending} onClick={()=>start(async()=>{const r=await updateAutonomyPolicyAction({workflow:p.workflow,mode:p.mode,spendingLimitCents:p.spending_limit_cents,discountLimitBps:p.discount_limit_bps,audienceLimit:p.audience_limit,approvalThresholdCents:p.approval_threshold_cents,emergencyStopped:p.emergency_stopped});setMsg(r.error??`${p.workflow} saved`)})} className="rounded-lg bg-gold px-3 py-2 font-black uppercase text-black">Save</button></td></tr>)}</tbody></table></div>{msg?<p className="mt-3 text-xs">{msg}</p>:null}</section>
 <section className="rounded-3xl border border-border bg-card p-5"><h2 className="text-xl font-black">Recommendation outcome ledger</h2><div className="mt-4 space-y-3">{outcomes.length?outcomes.map(o=><article key={o.id} className="rounded-2xl border border-border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-[9px] font-black uppercase text-gold-soft">{o.workflow} · {Math.round(Number(o.confidence)*100)}% confidence</p><h3 className="mt-1 font-black">{o.recommendation}</h3><p className="mt-1 text-xs text-muted-foreground">Predicted: {JSON.stringify(o.predicted_outcome)} · Actual: {o.evaluated_at?JSON.stringify(o.actual_result):'Not evaluated yet'}</p></div><div className="text-right text-xs"><p>{displayMoney(o.revenue_cents)} revenue</p><p>{displayMoney(o.margin_cents)} margin</p><p>{o.accuracy==null?'Accuracy pending':`${Math.round(Number(o.accuracy)*100)}% accurate`}</p></div></div>{o.owner_decision==='pending'?<div className="mt-3 flex gap-2">{(['accepted','ignored','rejected'] as const).map(d=><button key={d} onClick={()=>start(async()=>{await decideTitanRecommendationAction(o.id,d)})} className="rounded-lg border border-border px-3 py-2 text-[10px] font-black uppercase">{d}</button>)}</div>:<p className="mt-3 text-[10px] font-black uppercase text-muted-foreground">Owner decision: {o.owner_decision}</p>}</article>):<p className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No recommendations are shown as “learned” until a real outcome record exists.</p>}</div></section></div>
}
