'use client';
import { useMemo,useState,useTransition } from 'react';
import { AlertTriangle,Plus,Save,Trash2 } from 'lucide-react';
import { calculateOwnerQuote,type OwnerQuoteInput } from '@/lib/quotes/owner-quote';
import { displayMoney } from '@/lib/display-format';
import { saveOwnerQuoteAction } from '@/app/(dashboard)/admin/quotes/actions';
import { OwnerQuoteActions } from '@/components/admin/owner-quote-actions';

type Row=Record<string,any>;
const field='w-full rounded-xl border border-border bg-input px-3 py-2.5 text-sm text-foreground';
const numeric=(value:string)=>Math.max(0,Number(value)||0);
export function OwnerQuoteBuilder({customers,services,technicians,recent}:{customers:Row[];services:Row[];technicians:Row[];recent:Row[]}){
  const [pending,startTransition]=useTransition();const [message,setMessage]=useState('');const [customerId,setCustomerId]=useState('');
  const [prospect,setProspect]=useState({name:'',email:'',phone:''});const [serviceSlug,setServiceSlug]=useState(String(services[0]?.slug??''));
  const [vehicles,setVehicles]=useState([{description:'',size:'standard'}]);const [preferredStart,setPreferredStart]=useState('');const [technicianId,setTechnicianId]=useState('');const [notes,setNotes]=useState('');
  const service=services.find(row=>row.slug===serviceSlug)??services[0];const servicePrice=Number(service?.base_price_cents??service?.service_prices?.[0]?.price_cents??0);
  const [p,setP]=useState<OwnerQuoteInput>({catalogPriceCents:servicePrice,vehicleCount:1,vehicleSize:'standard',interiorCondition:1,exteriorCondition:1,dirtiness:1,petHair:false,stains:false,odor:false,excessiveTrash:false,paintCondition:1,addOnCents:0,travelMiles:0,promotionCents:0,membershipDiscountCents:0,creditCents:0,manualDiscountCents:0,taxRateBps:825,depositRateBps:3000,baseLaborMinutes:Number(service?.duration_minutes??120),availableMinutes:240});
  const calc=useMemo(()=>calculateOwnerQuote({...p,vehicleCount:vehicles.length}),[p,vehicles.length]);
  const setMoney=(key:keyof OwnerQuoteInput,value:string)=>setP(v=>({...v,[key]:Math.round(numeric(value)*100)}));
  const chooseService=(slug:string)=>{setServiceSlug(slug);const match=services.find(row=>row.slug===slug);setP(v=>({...v,catalogPriceCents:Number(match?.base_price_cents??match?.service_prices?.[0]?.price_cents??0),baseLaborMinutes:Number(match?.duration_minutes??120)}));};
  const save=()=>startTransition(async()=>{setMessage('');const result=await saveOwnerQuoteAction({customerId:customerId||undefined,prospect,serviceSlug,vehicles,pricing:{...p,vehicleCount:vehicles.length},preferredStart:preferredStart||undefined,technicianId:technicianId||undefined,notes});setMessage(result.error??`Quote saved. ${result.publicUrl}`);if(!result.error)location.reload();});
  return <div className="grid gap-5 2xl:grid-cols-[1fr_380px]">
    <div className="space-y-5">
      <section className="rounded-3xl border border-gold/25 bg-card p-5"><h2 className="text-lg font-black">Customer and appointment</h2><div className="mt-4 grid gap-3 md:grid-cols-3">
        <select className={`${field} md:col-span-2`} value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">New prospect</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone||c.email||'no contact'}</option>)}</select>
        <select className={field} value={technicianId} onChange={e=>setTechnicianId(e.target.value)}><option value="">Suggested technician</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.full_name||t.role}</option>)}</select>
        {!customerId?<><input className={field} placeholder="Prospect name" value={prospect.name} onChange={e=>setProspect({...prospect,name:e.target.value})}/><input className={field} placeholder="Phone" value={prospect.phone} onChange={e=>setProspect({...prospect,phone:e.target.value})}/><input className={field} placeholder="Email" value={prospect.email} onChange={e=>setProspect({...prospect,email:e.target.value})}/></>:null}
        <input type="datetime-local" className={field} value={preferredStart} onChange={e=>setPreferredStart(e.target.value)}/><input type="number" className={field} value={p.availableMinutes} onChange={e=>setP({...p,availableMinutes:numeric(e.target.value)})} aria-label="Available appointment minutes"/>
      </div></section>
      <section className="rounded-3xl border border-border bg-card p-5"><div className="flex justify-between"><h2 className="text-lg font-black">Vehicles and condition</h2><button type="button" onClick={()=>setVehicles([...vehicles,{description:'',size:'standard'}])} className="inline-flex items-center gap-1 text-xs font-black uppercase text-gold"><Plus className="h-4 w-4"/> Vehicle</button></div>
        <div className="mt-4 space-y-2">{vehicles.map((v,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_160px_42px]"><input className={field} placeholder="Year, make, model" value={v.description} onChange={e=>setVehicles(vehicles.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/><select className={field} value={v.size} onChange={e=>{const size=e.target.value as OwnerQuoteInput['vehicleSize'];setVehicles(vehicles.map((x,n)=>n===i?{...x,size}:x));if(i===0)setP({...p,vehicleSize:size})}}><option value="compact">Compact</option><option value="standard">Standard</option><option value="large">Large</option><option value="xl">XL</option></select><button disabled={vehicles.length===1} onClick={()=>setVehicles(vehicles.filter((_,n)=>n!==i))} className="rounded-xl border border-border p-2 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Interior', 'interiorCondition'],['Exterior','exteriorCondition'],['Dirtiness','dirtiness'],['Paint','paintCondition']].map(([label,key])=><label key={key} className="text-xs font-bold">{label}<select className={`${field} mt-1`} value={String(p[key as keyof OwnerQuoteInput])} onChange={e=>setP({...p,[key]:Number(e.target.value)})}>{[0,1,2,3,4].map(n=><option key={n} value={n}>{['Excellent','Light','Moderate','Heavy','Severe'][n]}</option>)}</select></label>)}</div>
        <div className="mt-4 flex flex-wrap gap-2">{([['petHair','Pet hair'],['stains','Stains'],['odor','Odor'],['excessiveTrash','Excessive trash']] as const).map(([key,label])=><label key={key} className={`cursor-pointer rounded-full border px-3 py-2 text-xs font-bold ${p[key]?'border-amber-400 bg-amber-400/10':'border-border'}`}><input className="mr-2" type="checkbox" checked={p[key]} onChange={e=>setP({...p,[key]:e.target.checked})}/>{label}</label>)}</div>
      </section>
      <section className="rounded-3xl border border-border bg-card p-5"><h2 className="text-lg font-black">Service economics</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-xs font-bold sm:col-span-2">Service<select className={`${field} mt-1`} value={serviceSlug} onChange={e=>chooseService(e.target.value)}>{services.map(s=><option key={s.slug} value={s.slug}>{s.title||s.name||s.slug}</option>)}</select></label>
        {[['Catalog / vehicle','catalogPriceCents'],['Add-ons','addOnCents'],['Promotion','promotionCents'],['Member discount','membershipDiscountCents'],['Referral / loyalty','creditCents'],['Manual discount','manualDiscountCents']].map(([label,key])=><label key={key} className="text-xs font-bold">{label}<input type="number" className={`${field} mt-1`} value={Number(p[key as keyof OwnerQuoteInput])/100} onChange={e=>setMoney(key as keyof OwnerQuoteInput,e.target.value)}/></label>)}
        <label className="text-xs font-bold">Travel miles<input type="number" className={`${field} mt-1`} value={p.travelMiles} onChange={e=>setP({...p,travelMiles:numeric(e.target.value)})}/></label><label className="text-xs font-bold">Tax %<input type="number" step=".01" className={`${field} mt-1`} value={p.taxRateBps/100} onChange={e=>setP({...p,taxRateBps:numeric(e.target.value)*100})}/></label><label className="text-xs font-bold">Deposit %<input type="number" className={`${field} mt-1`} value={p.depositRateBps/100} onChange={e=>setP({...p,depositRateBps:numeric(e.target.value)*100})}/></label>
      </div><textarea className={`${field} mt-4`} rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Water/power availability, access, customer notes"/></section>
    </div>
    <aside className="space-y-4 2xl:sticky 2xl:top-5 2xl:self-start"><section className="rounded-3xl border border-gold/30 bg-gradient-to-br from-[#171308] to-black p-5 text-white"><p className="text-[10px] font-black uppercase tracking-[.2em] text-gold-soft">Live quote</p><p className="mt-2 font-mono text-4xl font-black">{displayMoney(calc.totalCents)}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{[['Catalog',calc.catalogCents],['Condition',calc.conditionSurchargeCents],['Add-ons',calc.addOnCents],['Travel',calc.travelFeeCents],['Discounts',-calc.discountCents],['Tax',calc.taxCents],['Deposit',calc.depositCents],['Margin',calc.estimatedMarginCents]].map(([l,v])=><div key={String(l)}><p className="text-zinc-500">{l}</p><p className="font-mono font-black">{displayMoney(Number(v))}</p></div>)}</div><div className="mt-5 border-t border-white/10 pt-4 text-xs"><p>Labor: <b>{calc.laborMinutes} min</b></p><p>Minimum profitable: <b>{displayMoney(calc.minimumProfitableCents)}</b></p><p>Estimated completion: <b>{preferredStart?new Date(new Date(preferredStart).getTime()+calc.laborMinutes*60000).toLocaleString():'Select a start time'}</b></p></div>
        {calc.warnings.map(w=><p key={w} className="mt-3 flex gap-2 rounded-xl border border-amber-400/30 bg-amber-400/10 p-3 text-xs text-amber-100"><AlertTriangle className="h-4 w-4 shrink-0"/>{w}</p>)}
        <button disabled={pending} onClick={save} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gold py-3 text-xs font-black uppercase text-black disabled:opacity-50"><Save className="h-4 w-4"/>{pending?'Saving…':'Save and preview'}</button>{message?<p className="mt-3 text-xs">{message}</p>:null}
      </section>
      <section className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-black uppercase">Recent quotes</p><div className="mt-2 space-y-2">{recent.slice(0,8).map(q=><OwnerQuoteActions key={q.id} quote={q as any}/>)}</div></section>
    </aside>
  </div>;
}
