'use client';
import { useState,useTransition } from 'react';
import Link from 'next/link';
import { Copy,ExternalLink,Send,CalendarCheck,CreditCard,MoreHorizontal } from 'lucide-react';
import { useOutboundPreview } from '@/components/admin/outbound-message-provider';
import { buildToneVariants } from '@/lib/outbound-message-tones';
import { displayMoney } from '@/lib/display-format';
import { convertOwnerQuoteAction,createOwnerQuotePaymentAction,previewOwnerQuoteMessageAction,quoteLifecycleAction,sendOwnerQuoteAction } from '@/app/(dashboard)/admin/quotes/actions';
type Q={id:string;status:string;customer_name:string;customer_email?:string|null;customer_phone?:string|null;total_cents:number;deposit_cents:number;estimated_margin_cents:number;labor_minutes:number;access_token:string;appointment_id?:string|null};
export function OwnerQuoteActions({quote}:{quote:Q}){const {openPreview}=useOutboundPreview();const [pending,start]=useTransition();const [msg,setMsg]=useState('');
 const message=async(channel:'sms'|'email')=>{const p=await previewOwnerQuoteMessageAction(quote.id);if(p.error||!p.quote){setMsg(p.error??'Preview unavailable');return}const recipient=channel==='sms'?p.quote.customerPhone:p.quote.customerEmail;if(!recipient){setMsg(`No ${channel==='sms'?'phone':'email'} on this quote.`);return}const base=channel==='sms'?p.sms!:p.email!;openPreview({title:'Send secure quote',channel,channelOptions:['sms','email'],recipient,body:base,subject:p.subject,priceCents:quote.total_cents,durationMinutes:quote.labor_minutes,contextLabel:`${quote.customer_name} · deposit ${displayMoney(quote.deposit_cents)}`,toneVariants:buildToneVariants(base,{name:quote.customer_name,price:displayMoney(quote.total_cents),bookLink:p.publicUrl}),allowSchedule:true,onSend:final=>sendOwnerQuoteAction({id:quote.id,channel:final.channel,subject:final.subject,body:final.body}),onSchedule:final=>sendOwnerQuoteAction({id:quote.id,channel:final.channel,subject:final.subject,body:final.body,scheduleAt:final.scheduledFor})})};
 const act=(action:'duplicate'|'expire'|'void'|'accept'|'decline')=>start(async()=>{if(['void','expire','decline'].includes(action)&&!confirm(`Confirm ${action} for this quote?`))return;const r=await quoteLifecycleAction({id:quote.id,action});setMsg(r.error??`${action} complete`);if(!r.error)location.reload()});
 const convert=()=>start(async()=>{const r=await convertOwnerQuoteAction(quote.id);setMsg(r.error??(r.calendarError?`Booked; Google Calendar: ${r.calendarError}`:`Booking created: ${r.appointmentId}`));if(!r.error)location.reload()});
 const pay=(kind:'deposit'|'full'|'arrival')=>start(async()=>{const r=await createOwnerQuotePaymentAction({id:quote.id,kind});const url='url' in r?r.url:undefined;setMsg(r.error??(url?'Payment link created':'Pay on arrival saved'));if(url)location.href=url});
 return <article className="rounded-xl border border-border p-3 text-xs"><div className="flex flex-wrap justify-between gap-3"><span><b>{quote.customer_name}</b><small className="block text-muted-foreground">{quote.status} · {quote.labor_minutes||0} min · margin {displayMoney(quote.estimated_margin_cents||0)}</small></span><b>{displayMoney(quote.total_cents)}</b></div><div className="mt-3 flex flex-wrap gap-2">
 <Link href={`/estimate/${quote.access_token}`} target="_blank" className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1.5"><ExternalLink className="h-3 w-3"/>Preview</Link>
 <Link href={`/api/estimates/${quote.id}/pdf`} className="rounded-lg border border-border px-2 py-1.5">PDF</Link>
 <button onClick={()=>navigator.clipboard.writeText(`${location.origin}/estimate/${quote.access_token}`)} className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1.5"><Copy className="h-3 w-3"/>Copy link</button>
 <button onClick={()=>message('sms')} className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1.5"><Send className="h-3 w-3"/>SMS</button><button onClick={()=>message('email')} className="rounded-lg border border-border px-2 py-1.5">Email</button>
 {['approved','deposit_paid'].includes(quote.status)&&!quote.appointment_id?<button disabled={pending} onClick={convert} className="inline-flex items-center gap-1 rounded-lg bg-gold px-2 py-1.5 font-black text-black"><CalendarCheck className="h-3 w-3"/>Convert</button>:null}
 {['approved','converted','deposit_paid'].includes(quote.status)?<><button onClick={()=>pay('deposit')} className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1.5"><CreditCard className="h-3 w-3"/>Deposit</button><button onClick={()=>pay('full')} className="rounded-lg border border-border px-2 py-1.5">Pay full</button><button onClick={()=>pay('arrival')} className="rounded-lg border border-border px-2 py-1.5">Pay arrival</button></>:null}
 <details><summary className="cursor-pointer list-none rounded-lg border border-border p-1.5"><MoreHorizontal className="h-3 w-3"/></summary><div className="absolute z-20 mt-1 flex flex-col rounded-xl border border-border bg-card p-2 shadow-xl">{quote.status==='draft'?<button onClick={()=>act('accept')} className="px-3 py-2 text-left">Mark accepted</button>:null}<button onClick={()=>act('duplicate')} className="px-3 py-2 text-left">Duplicate</button><button onClick={()=>act('decline')} className="px-3 py-2 text-left">Decline</button><button onClick={()=>act('expire')} className="px-3 py-2 text-left">Expire</button><button onClick={()=>act('void')} className="px-3 py-2 text-left text-rose-400">Void</button></div></details>
 </div>{msg?<p className="mt-2 text-amber-300">{msg}</p>:null}</article>}
