-- Fix profiles SELECT failing for all users (often super_admin first to notice):
-- Policy `profiles_select_self` uses `public.is_staff()`, which calls `current_role()`,
-- which SELECTs `public.profiles` again under the same RLS session → PostgreSQL can
-- raise "infinite recursion detected in policy for relation profiles" (PostgREST surfaces
-- this as a generic read error → app shows PROFILE_FETCH_ERROR on login).
--
-- `ALTER FUNCTION ... SET (row_security = off)` is not valid PostgreSQL syntax.
-- The helpers are created as SECURITY DEFINER with a pinned search_path in 000001;
-- 000006 removes the recursive profiles policy that caused this issue.
